import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'flex-start',
      alignItems: 'center',
      backgroundColor: '#494848',
      paddingTop: 30,
      paddingBottom: 20,
      paddingLeft: 20,
      paddingRight: 20,
      width: '100%',
      height: '100%',
    },
    headerContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 10,
      backgroundColor: '#909090',
      paddingHorizontal: 40,
      paddingVertical: 10,
      borderRadius: 40,
      margin: 5,
    },
    headerText: {
      fontSize: 25,
      fontWeight: 'bold',
      color: '#fff',
    },
    inputContainer: {
      flexDirection: 'row',
      gap: 10,
      alignItems: 'center',
      marginBottom: 20,
      marginTop: 20,
    },
    valueBox: {
      height: 55,
      borderColor: '#fff',
      color: '#fff',
      borderWidth: 1,
      width: '40%',
      paddingLeft: 20,
      marginBottom: 15,
      borderRadius: 20,
      fontSize: 18,
    },
    picker: {
      height: 55,
      color: '#fff',
      width: '55%',
      paddingLeft: 10,
      marginBottom: 15,
      borderRadius: 20,
    },
    buttonsContainer: {
      flexDirection: 'row',
      gap: 15,
      alignItems: 'center',
      marginBottom: 20,
    },
    defaultButton: {
        backgroundColor: '#636363',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 20,
        marginBottom: 20,
      },
      defaultButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
      },
    listContainer: {
        flex: 1,  
        justifyContent: 'flex-end',  
        width: '100%',
        paddingBottom: 20,
    },
    itemContainer: {
      backgroundColor: '#909090',
      paddingVertical: 10,
      paddingHorizontal: 15,
      borderRadius: 10,
      marginBottom: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
    },
    itemTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#fff',
    },
    itemValue: {
      fontSize: 18,
      color: '#fff',
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContainer: {
      backgroundColor: '#494848',
      padding: 30,
      borderRadius: 10,
      alignItems: 'center',
    },
    monthSelectorContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
      paddingHorizontal: 20,
      marginVertical: 20,
    },
    monthSelectorText: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#fff',
    },
    detailsListContainer: {
      flex: 1,
      justifyContent: 'flex-start',  
      width: '100%',
    },
    scrollViewContainer: {
        flex: 1,
      },
  });